#!/usr/bin/env bash

script_dir=$(readlink -e "$(dirname "$0")")
root_dir=$(readlink -e "${script_dir}/..")

cd "$script_dir"

export PYTHONPATH="${root_dir}/robotframework-httplibrary/src:${PYTHONPATH}"

robot "$@" .
