#!/usr/bin/env bash

if [[ -z "$APPDAEMON_PATH" ]]; then
    echo "APPDAEMON_PATH must be set." >&2
    exit 1
fi

script_dir=$(dirname "$(readlink -e "$0")")

source "${APPDAEMON_PATH}/bin/activate"

python "${script_dir}/TestAppDaemon.py" "$@"

