#!/usr/bin/env bash

script_dir=$(readlink -e "$(dirname "$0")")
root_dir=$(readlink -e "${script_dir}/../..")

cd "$script_dir"
mkdir -p output

export PYTHONPATH="${script_dir}:${root_dir}/robotframework-httplibrary/src:${PYTHONPATH}"
export TZ=Europe/Budapest

exec pabot --testlevelsplit --processes 8 --outputdir=output "$@" .
