version: 2.1
commands:
  pytest:
    parameters:
      directory:
        type: string
    steps:
      - run:
          name: run tests
          command: |
            /test/bin/pytest <<parameters.directory>> -v \
                --tb=short
      - store_artifacts:
          path: <<parameters.directory>>/output
          when: on_fail

jobs:
  appdaemon-unit-test:
    docker:
      - image: kangirigungi/home-assistant-config-test:pytest
    environment:
      - TEST_PYTHON: /test/bin/python
    steps:
      - checkout
      - pytest:
          directory: test/appdaemon_unit_test

  appdaemon-integration-test:
    docker:
      - image: kangirigungi/home-assistant-config-test:pytest
    environment:
      - HASS_PATH: /homeassistant
      - APPDAEMON_PATH: /appdaemon
    steps:
      - checkout
      - run:
          command: git submodule update --init --recursive
      - pytest:
          directory: test/appdaemon_integration_test

workflows:
  version: 2
  test:
    jobs:
      - appdaemon-unit-test
      - appdaemon-integration-test
