#!/usr/bin/env bash

script_dir=$(readlink -e "$(dirname "$0")")
root_dir=$(readlink -e "${script_dir}/../..")

cd "$script_dir"

export PYTHONPATH="${script_dir}:${root_dir}/robotframework-httplibrary/src:${PYTHONPATH}"
export TZ=Europe/Budapest

output_dir="${PWD}/output"
mkdir -p "${output_dir}"
exec python -m robot --outputdir="${output_dir}" --variable "base_output_directory:${output_dir}" "$@" .
