- trigger:
      platform: mqtt
      topic: home/input_select/light_driveway/set
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.light_driveway
            option: '{{ trigger.payload }}'

- trigger:
      platform: mqtt
      topic: home/input_select/light_garage/set
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.light_garage
            option: '{{ trigger.payload }}'

- trigger:
      platform: mqtt
      topic: home/input_select/light_gate_reflector/set
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.light_gate_reflector
            option: '{{ trigger.payload }}'

- trigger:
      platform: mqtt
      topic: home/input_select/light_christmas_front/set
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.light_christmas_front
            option: '{{ trigger.payload }}'

- trigger:
      platform: mqtt
      topic: home/input_select/light_christmas_tree/set
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.light_christmas_tree
            option: '{{ trigger.payload }}'

- trigger:
      platform: mqtt
      topic: home/input_select/light_outside_1/set
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.light_outside_1
            option: '{{ trigger.payload }}'

- trigger:
      platform: mqtt
      topic: home/input_select/light_outside_2/set
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.light_outside_2
            option: '{{ trigger.payload }}'

- trigger:
      platform: mqtt
      topic: home/input_select/light_outside_3/set
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.light_outside_3
            option: '{{ trigger.payload }}'

- trigger:
      platform: mqtt
      topic: home/input_select/light_outside_4/set
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.light_outside_4
            option: '{{ trigger.payload }}'

- trigger:
      platform: mqtt
      topic: home/input_select/light_outside_5/set
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.light_outside_5
            option: '{{ trigger.payload }}'

- trigger:
      platform: mqtt
      topic: home/input_select/light_outside_6/set
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.light_outside_6
            option: '{{ trigger.payload }}'

- trigger:
      platform: mqtt
      topic: home/input_select/hot_water_pump/set
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.hot_water_pump
            option: '{{ trigger.payload }}'

- trigger:
      platform: mqtt
      topic: home/input_select/mosquito_killer_bedroom/set
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.mosquito_killer_bedroom
            option: '{{ trigger.payload }}'

- trigger:
      platform: mqtt
      topic: home/input_select/presence_mode/set
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.presence_mode
            option: '{{ trigger.payload }}'

- trigger:
      platform: zone
      entity_id: device_tracker.homeassistant_owntrackssamsung
      zone: zone.home
      event: leave
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.presence_mode
            option: 'away'

- trigger:
      platform: state
      entity_id: binary_sensor.door_main_entrance
      from: 'off'
      to: 'on'
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.presence_mode
            option: 'home'

- trigger:
      platform: zone
      entity_id: device_tracker.homeassistant_owntrackssamsung
      zone: zone.home
      event: enter
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.presence_mode
            option: 'home'

- trigger:
      platform: state
      entity_id: binary_sensor.door_attic_hatch
      from: 'off'
      to: 'on'
  action:
      - service: homeassistant.turn_on
        data_template:
            entity_id: switch.light_attic_downstairs

- trigger:
      platform: state
      entity_id: binary_sensor.door_attic_hatch
      from: 'on'
      to: 'off'
  action:
      - service: homeassistant.turn_off
        data_template:
            entity_id: switch.light_attic_downstairs
      - service: homeassistant.turn_off
        data_template:
            entity_id: switch.light_attic_upstairs
