- alias: bejáró világítás MQTT
  trigger:
      platform: mqtt
      topic: home/input_select/light_driveway/set
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.light_driveway
            option: '{{ trigger.payload }}'

- alias: garázs világítás MQTT
  trigger:
      platform: mqtt
      topic: home/input_select/light_garage/set
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.light_garage
            option: '{{ trigger.payload }}'

- alias: kapu világítás MQTT
  trigger:
      platform: mqtt
      topic: home/input_select/light_gate_reflector/set
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.light_gate_reflector
            option: '{{ trigger.payload }}'

- alias: karácsonyi világítás eresz alatt MQTT
  trigger:
      platform: mqtt
      topic: home/input_select/light_christmas_front/set
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.light_christmas_front
            option: '{{ trigger.payload }}'

- alias: karácsonyi világítás fenyőfa MQTT
  trigger:
      platform: mqtt
      topic: home/input_select/light_christmas_tree/set
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.light_christmas_tree
            option: '{{ trigger.payload }}'

- alias: körvilágítás 1 MQTT
  trigger:
      platform: mqtt
      topic: home/input_select/light_outside_1/set
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.light_outside_1
            option: '{{ trigger.payload }}'

- alias: körvilágítás 2 MQTT
  trigger:
      platform: mqtt
      topic: home/input_select/light_outside_2/set
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.light_outside_2
            option: '{{ trigger.payload }}'

- alias: körvilágítás 3 MQTT
  trigger:
      platform: mqtt
      topic: home/input_select/light_outside_3/set
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.light_outside_3
            option: '{{ trigger.payload }}'

- alias: körvilágítás 4 MQTT
  trigger:
      platform: mqtt
      topic: home/input_select/light_outside_4/set
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.light_outside_4
            option: '{{ trigger.payload }}'

- alias: körvilágítás 5 MQTT
  trigger:
      platform: mqtt
      topic: home/input_select/light_outside_5/set
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.light_outside_5
            option: '{{ trigger.payload }}'

- alias: körvilágítás 6 MQTT
  trigger:
      platform: mqtt
      topic: home/input_select/light_outside_6/set
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.light_outside_6
            option: '{{ trigger.payload }}'

- alias: melegvíz keringető MQTT
  trigger:
      platform: mqtt
      topic: home/input_select/hot_water_pump/set
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.hot_water_pump
            option: '{{ trigger.payload }}'

- alias: szúnyogirtó MQTT
  trigger:
      platform: mqtt
      topic: home/input_select/mosquito_killer_bedroom/set
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.mosquito_killer_bedroom
            option: '{{ trigger.payload }}'

- alias: jelenlét mód MQTT
  trigger:
      platform: mqtt
      topic: home/input_select/presence_mode/set
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.presence_mode
            option: '{{ trigger.payload }}'

- alias: elmenés
  trigger:
      platform: state
      entity_id: person.peti
      to: 'not_home'
      for: '00:01:00'
  condition:
    condition: state
    entity_id: input_select.presence_mode
    state: 'home'
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.presence_mode
            option: 'away'

- alias: bejárati ajtó nyitás
  trigger:
      platform: state
      entity_id: binary_sensor.door_main_entrance
      from: 'off'
      to: 'on'
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.presence_mode
            option: 'home'

- alias: hazajövés
  trigger:
    - platform: zone
      entity_id: person.peti
      zone: zone.home
      event: enter
    - platform: template
      value_template: !secret wifi_sensor_template
  condition:
    condition: state
    entity_id: input_select.presence_mode
    state: 'away'
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.presence_mode
            option: 'home'

- alias: padlásfeljáró nyitás
  trigger:
      platform: state
      entity_id: binary_sensor.door_attic_hatch
      from: 'off'
      to: 'on'
  action:
      - service: homeassistant.turn_on
        data_template:
            entity_id: switch.light_attic_downstairs

- alias: padlásfeljáró zárás
  trigger:
      platform: state
      entity_id: binary_sensor.door_attic_hatch
      from: 'on'
      to: 'off'
  action:
      - service: homeassistant.turn_off
        data_template:
            entity_id: switch.light_attic_downstairs
      - service: homeassistant.turn_off
        data_template:
            entity_id: switch.light_attic_upstairs

- alias: gázfűtés ki jelenlét váltásnál
  trigger:
      platform: state
      entity_id: input_select.presence_mode
      to: 'home'
  condition:
      condition: state
      entity_id: input_boolean.wood_heating
      state: 'on'
  action:
      - service: climate.set_hvac_mode
        data:
            entity_id: climate.heater
            hvac_mode: 'off'

- alias: gázfűtés be
  trigger:
      platform: state
      entity_id: input_select.presence_mode
      from: 'home'
  condition:
      condition: state
      entity_id: input_boolean.wood_heating
      state: 'on'
  action:
      - service: climate.set_hvac_mode
        data:
            entity_id: climate.heater
            hvac_mode: 'heat'

- alias: gázfűtés ki fafűtés váltásnál
  trigger:
      platform: state
      entity_id: input_boolean.wood_heating
      from: 'off'
      to: 'on'
  condition:
      condition: state
      entity_id: input_select.presence_mode
      state: 'home'
  action:
      - service: climate.set_hvac_mode
        data:
            entity_id: climate.heater
            hvac_mode: 'off'

- alias: alvás RFID
  trigger:
      platform: event
      event_type: tag_scanned
      event_data:
          tag_id: !secret sleep_tag_id
  condition:
      condition: state
      entity_id: input_select.presence_mode
      state: 'home'
  action:
      - service: input_select.select_option
        data:
            entity_id: input_select.presence_mode
            option: sleep

- alias: ebédlő redőny nyitás
  trigger:
      platform: state
      entity_id: sensor.dining_room_window_blind_state
      to: 'open'
      for: '00:00:30'
  action:
      - service: cover.open_cover
        data:
            entity_id: cover.dining_room

- alias: ebédlő redőny zárás
  trigger:
      platform: state
      entity_id: sensor.dining_room_window_blind_state
      to: 'closed'
      for: '00:00:30'
  action:
      - service: cover.close_cover
        data:
            entity_id: cover.dining_room

- alias: nappali redőny nyitás
  trigger:
      platform: state
      entity_id: sensor.living_room_window_blind_state
      to: 'open'
      for: '00:00:10'
  action:
      - service: cover.open_cover
        data:
            entity_id: cover.living_room

- alias: nappali redőny zárás
  trigger:
      platform: state
      entity_id: sensor.living_room_window_blind_state
      to: 'closed'
      for: '00:00:10'
  action:
      - service: cover.close_cover
        data:
            entity_id: cover.living_room

- alias: nappali redőny résre nyitás
  trigger:
      platform: state
      entity_id: sensor.living_room_window_blind_state
      to: 'half'
      for: '00:00:10'
  action:
      - service: cover.set_cover_position
        data:
            entity_id: cover.living_room
            position: 45

- alias: pince locsolás manuális ki
  trigger:
      platform: state
      entity_id: switch.auto_sprinkler_cellar
      to: 'off'
  action:
      - service: input_boolean.turn_off
        data:
            entity_id: input_boolean.start_sprinkler_cellar

- alias: terasz locsolás kihagyása
  trigger:
      platform: state
      entity_id: input_boolean.skip_balcony_watering
      to: 'on'
  action:
      - service: input_select.select_option
        data:
            entity_id: input_select.balcony_sprinkler
            option: 'off'

- alias: terasz locsolás folytatás
  trigger:
    platform: state
    entity_id: sensor.time
    to: '00:00'
  condition:
    condition: state
    entity_id: input_boolean.skip_balcony_watering
    state: 'on'
  action:
    - service: input_select.select_option
      data:
          entity_id: input_select.balcony_sprinkler
          option: 'auto'
    - service: input_boolean.turn_off
      data:
          entity_id: input_boolean.skip_balcony_watering
