- alias: bejáró világítás MQTT
  trigger:
      platform: mqtt
      topic: home/input_select/light_driveway/set
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.light_driveway
            option: '{{ trigger.payload }}'

- alias: garázs világítás MQTT
  trigger:
      platform: mqtt
      topic: home/input_select/light_garage/set
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.light_garage
            option: '{{ trigger.payload }}'

- alias: kapu világítás MQTT
  trigger:
      platform: mqtt
      topic: home/input_select/light_gate_reflector/set
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.light_gate_reflector
            option: '{{ trigger.payload }}'

- alias: karácsonyi világítás eresz alatt MQTT
  trigger:
      platform: mqtt
      topic: home/input_select/light_christmas_front/set
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.light_christmas_front
            option: '{{ trigger.payload }}'

- alias: karácsonyi világítás fenyőfa MQTT
  trigger:
      platform: mqtt
      topic: home/input_select/light_christmas_tree/set
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.light_christmas_tree
            option: '{{ trigger.payload }}'

- alias: körvilágítás 1 MQTT
  trigger:
      platform: mqtt
      topic: home/input_select/light_outside_1/set
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.light_outside_1
            option: '{{ trigger.payload }}'

- alias: körvilágítás 2 MQTT
  trigger:
      platform: mqtt
      topic: home/input_select/light_outside_2/set
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.light_outside_2
            option: '{{ trigger.payload }}'

- alias: körvilágítás 3 MQTT
  trigger:
      platform: mqtt
      topic: home/input_select/light_outside_3/set
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.light_outside_3
            option: '{{ trigger.payload }}'

- alias: körvilágítás 4 MQTT
  trigger:
      platform: mqtt
      topic: home/input_select/light_outside_4/set
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.light_outside_4
            option: '{{ trigger.payload }}'

- alias: körvilágítás 5 MQTT
  trigger:
      platform: mqtt
      topic: home/input_select/light_outside_5/set
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.light_outside_5
            option: '{{ trigger.payload }}'

- alias: körvilágítás 6 MQTT
  trigger:
      platform: mqtt
      topic: home/input_select/light_outside_6/set
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.light_outside_6
            option: '{{ trigger.payload }}'

- alias: melegvíz keringető MQTT
  trigger:
      platform: mqtt
      topic: home/input_select/hot_water_pump/set
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.hot_water_pump
            option: '{{ trigger.payload }}'

- alias: szúnyogirtó MQTT
  trigger:
      platform: mqtt
      topic: home/input_select/mosquito_killer_bedroom/set
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.mosquito_killer_bedroom
            option: '{{ trigger.payload }}'

- alias: jelenlét mód MQTT
  trigger:
      platform: mqtt
      topic: home/input_select/presence_mode/set
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.presence_mode
            option: '{{ trigger.payload }}'

- alias: elmenés
  trigger:
      platform: state
      entity_id: person.peti
      to: 'not_home'
      for: '00:01:00'
  condition:
    and:
      - condition: state
        entity_id: input_select.presence_mode
        state: 'home'
      - not:
        - condition: template
          value_template: !secret wifi_sensor_template
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.presence_mode
            option: 'away'

- alias: bejárati ajtó nyitás
  trigger:
      platform: state
      entity_id: binary_sensor.door_main_entrance
      from: 'off'
      to: 'on'
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.presence_mode
            option: 'home'

- alias: hazajövés
  trigger:
    - platform: zone
      entity_id: person.peti
      zone: zone.home
      event: enter
    - platform: template
      value_template: !secret wifi_sensor_template
  condition:
    condition: state
    entity_id: input_select.presence_mode
    state: 'away'
  action:
      - service: input_select.select_option
        data_template:
            entity_id: input_select.presence_mode
            option: 'home'

- alias: padlásfeljáró nyitás
  trigger:
      platform: state
      entity_id: binary_sensor.door_attic_hatch
      from: 'off'
      to: 'on'
  action:
      - service: homeassistant.turn_on
        data_template:
            entity_id: switch.light_attic_downstairs

- alias: padlásfeljáró zárás
  trigger:
      platform: state
      entity_id: binary_sensor.door_attic_hatch
      from: 'on'
      to: 'off'
  action:
      - service: homeassistant.turn_off
        data_template:
            entity_id: switch.light_attic_downstairs
      - service: homeassistant.turn_off
        data_template:
            entity_id: switch.light_attic_upstairs

- alias: alvás RFID
  trigger:
      platform: event
      event_type: tag_scanned
      event_data:
          tag_id: !secret sleep_tag_id
  condition:
      condition: state
      entity_id: input_select.presence_mode
      state: 'home'
  action:
      - service: input_select.select_option
        data:
            entity_id: input_select.presence_mode
            option: sleep

- alias: pince locsolás manuális ki
  trigger:
      platform: state
      entity_id: switch.auto_sprinkler_cellar
      to: 'off'
  action:
      - service: input_boolean.turn_off
        data:
            entity_id: input_boolean.start_sprinkler_cellar

- alias: terasz locsolás kihagyása
  trigger:
      platform: state
      entity_id: input_boolean.skip_balcony_watering
      to: 'on'
  action:
      - service: input_select.select_option
        data:
            entity_id: input_select.balcony_sprinkler
            option: 'off'

- alias: terasz locsolás folytatás
  trigger:
    platform: state
    entity_id: sensor.time
    to: '00:00'
  condition:
    condition: state
    entity_id: input_boolean.skip_balcony_watering
    state: 'on'
  action:
    - service: input_select.select_option
      data:
          entity_id: input_select.balcony_sprinkler
          option: 'auto'
    - service: input_boolean.turn_off
      data:
          entity_id: input_boolean.skip_balcony_watering

- alias: klíma off
  trigger:
    platform: state
    entity_id: input_select.climate_mode
    to: 'off'
  action:
    - service: climate.set_hvac_mode
      target:
        entity_id:
          - climate.daikin_bedroom
          - climate.daikin_living_room
      data:
        hvac_mode: "off"

- alias: klíma auto
  trigger:
    platform: state
    entity_id: input_select.climate_mode
    to: 'auto'
  action:
    - service: climate.set_temperature
      target:
        entity_id:
          - climate.daikin_living_room
          - climate.daikin_bedroom
      data:
        hvac_mode: heat
        temperature: "{{ states('sensor.heater_target') | float(18) }}"
    - service: climate.set_fan_mode
      target:
        entity_id:
          - climate.daikin_living_room
          - climate.daikin_bedroom
      data:
        fan_mode: Auto
    - service: climate.set_swing_mode
      target:
        entity_id:
          - climate.daikin_living_room
          - climate.daikin_bedroom
      data:
        swing_mode: Vertical

- alias: klíma felfűtés
  trigger:
    platform: state
    entity_id: input_select.climate_mode
    to:
      - 'heat_up'
      - 'keep_warm'
  action:
    - service: climate.set_temperature
      target:
        entity_id:
          - climate.daikin_living_room
          - climate.daikin_bedroom
      data:
        hvac_mode: heat
        temperature: "{{ states('sensor.heater_target') | float(18) }}"
    - service: climate.set_fan_mode
      target:
        entity_id:
          - climate.daikin_living_room
          - climate.daikin_bedroom
      data:
        fan_mode: 5
    - service: climate.set_swing_mode
      target:
        entity_id:
          - climate.daikin_living_room
          - climate.daikin_bedroom
      data:
        swing_mode: Vertical

- alias: klíma melegen tartás be
  trigger:
    platform: state
    entity_id: sensor.time
    to: '13:00'
  condition:
    and:
      - condition: numeric_state
        entity_id: sensor.heater_check
        below: 12
      - condition: state
        entity_id: input_select.presence_mode
        state: 'away'
  action:
    - service: input_select.select_option
      target:
        entity_id: input_select.climate_mode
      data:
        option: 'keep_warm'

- alias: klíma melegen tartás ki
  trigger:
    platform: state
    entity_id: input_select.climate_mode
    to: 'keep_warm'
    for: '03:00:00'
  action:
    - service: input_select.select_option
      target:
        entity_id: input_select.climate_mode
      data:
        option: 'off'

- alias: hazajövés klíma kikapcsolás
  trigger:
    platform: state
    entity_id: input_select.presence_mode
    from: 'away'
    to: 'home'
  condition:
    and:
      - condition: state
        entity_id: input_boolean.wood_heating
        state: 'on'
      - condition: state
        entity_id: input_select.climate_mode
        state: 'heat_up'
  action:
    - service: input_select.select_option
      target:
        entity_id: input_select.climate_mode
      data:
        option: 'off'

- alias: hazajövés klíma auto
  trigger:
    platform: state
    entity_id: input_select.presence_mode
    from: 'away'
    to: 'home'
  condition:
    and:
      - condition: state
        entity_id: input_boolean.wood_heating
        state: 'off'
      - condition: state
        entity_id: input_select.climate_mode
        state: 'heat_up'
  action:
    - service: input_select.select_option
      target:
        entity_id: input_select.climate_mode
      data:
        option: 'auto'

- alias: zene bekapcsolás
  trigger:
    platform: state
    entity_id: sensor.time
    to: '07:05'
  condition:
    condition: state
    entity_id: input_select.presence_mode
    state: 'home'
  action:
    - service: homeassistant.turn_on
      data_template:
          entity_id: switch.desktop_player

- alias: szünet be
  trigger:
    platform: state
    entity_id: input_boolean.desktop_player_pause
    to: 'on'
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: switch.desktop_player

- alias: szünet ki
  trigger:
    platform: state
    entity_id: input_boolean.desktop_player_pause
    to: 'on'
    for: '00:07:00'
  action:
    - service: homeassistant.turn_on
      data:
        entity_id: switch.desktop_player
    - service: homeassistant.turn_off
      data:
        entity_id: input_boolean.desktop_player_pause

- alias: szünet leállítás
  trigger:
    platform: state
    entity_id: switch.desktop_player
    to: 'on'
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: input_boolean.desktop_player_pause

- alias: cupsd restart
  trigger:
    platform: state
    entity_id: binary_sensor.cups_available
    to: 'off'
  action:
    - service: notify.restart_cups
      data:
        message: a

- alias: cupsd restart
  trigger:
    platform: state
    entity_id: sensor.apc_input_voltage
    to: 'unavailable'
  action:
    - service: notify.restart_upsd
      data:
        message: a
