title: Home
views:
  - path: default_view
    title: default_view
    badges: []
    cards:
      - type: entities
        state_color: true
        entities:
          - binary_sensor.door_attic_hatch
          - binary_sensor.door_main_entrance
        title: Ajtók
        show_header_toggle: false
      - type: entities
        entities:
          - sensor.date
          - sensor.time
        title: Idő
      - type: entities
        entities:
          - sensor.temperature_furnace_gas
          - sensor.temperature_furnace_wood
          - sensor.temperature_furnace_wood_in
          - sensor.temperature_hot_water
          - switch.heating_pump
          - sensor.water_usage_dishwasher
          - sensor.temperature_dishwasher
          - sensor.water_usage
        title: Gépészet
        show_header_toggle: false
      - type: entities
        entities:
          - input_boolean.hot_water_pump
          - switch.hot_water_pump
          - input_select.hot_water_pump
          - input_datetime.hot_water_monday
          - input_datetime.hot_water_tuesday
          - input_datetime.hot_water_wednesday
          - input_datetime.hot_water_thursday
          - input_datetime.hot_water_friday
          - input_datetime.hot_water_saturday
          - input_datetime.hot_water_sunday
          - sensor.temperature_hot_water
        state_color: true
        title: Melegvíz bekapcsolás
        show_header_toggle: false
    icon: 'mdi:home'
  - path: garden
    title: 'Kert'
    icon: 'mdi:tree'
    cards:
      - type: button
        entity: switch.well
        state_color: true
      - type: button
        entity: input_boolean.sprinkler
        state_color: true
      - type: sensor
        entity: sensor.temperature_outside
        graph: line
      - type: horizontal-stack
        cards:
          - type: button
            entity: switch.auto_sprinkler1
            state_color: true
            tap_action:
              action: call-service
              service: script.auto_switch_manual
              service_data:
                auto_switch: input_select.auto_sprinkler1
                target: switch.auto_sprinkler1
            hold_action:
              action: call-service
              service: input_select.select_option
              service_data:
                entity_id: input_select.auto_sprinkler1
                option: 'auto'
          - type: button
            entity: switch.auto_sprinkler2
            state_color: true
            tap_action:
              action: call-service
              service: script.auto_switch_manual
              service_data:
                auto_switch: input_select.auto_sprinkler2
                target: switch.auto_sprinkler2
            hold_action:
              action: call-service
              service: input_select.select_option
              service_data:
                entity_id: input_select.auto_sprinkler2
                option: 'auto'
          - type: button
            entity: switch.auto_sprinkler3
            state_color: true
            tap_action:
              action: call-service
              service: script.auto_switch_manual
              service_data:
                auto_switch: input_select.auto_sprinkler3
                target: switch.auto_sprinkler3
            hold_action:
              action: call-service
              service: input_select.select_option
              service_data:
                entity_id: input_select.auto_sprinkler3
                option: 'auto'
      - type: entities
        state_color: true
        entities:
          - input_select.auto_sprinkler1
          - input_select.auto_sprinkler2
          - input_select.auto_sprinkler3
        show_header_toggle: false
      - type: entities
        entities:
          - sensor.maximum_temperature_last_day
          - sensor.rain_last_day
          - sensor.rain_last_7_days
          - sensor.sprinkler_run_time
        show_header_toggle: false
  - path: lights
    title: 'Világítás'
    icon: 'mdi:lightbulb'
    cards:
      - type: entities
        entities:
          - input_select.lighting_mode
      - type: horizontal-stack
        cards:
          - type: button
            entity: switch.light_attic_downstairs
            state_color: true
          - type: button
            entity: switch.light_attic_upstairs
            state_color: true
      - type: horizontal-stack
        cards:
          - type: button
            entity: switch.light_gate_reflector
            state_color: true
            tap_action:
              action: call-service
              service: script.auto_switch_manual
              service_data:
                auto_switch: input_select.light_gate_reflector
                target: switch.light_gate_reflector
            hold_action:
              action: call-service
              service: input_select.select_option
              service_data:
                entity_id: input_select.light_gate_reflector
                option: 'auto'
          - type: button
            entity: switch.light_driveway
            state_color: true
            tap_action:
              action: call-service
              service: script.auto_switch_manual
              service_data:
                auto_switch: input_select.light_driveway
                target: switch.light_driveway
            hold_action:
              action: call-service
              service: input_select.select_option
              service_data:
                entity_id: input_select.light_driveway
                option: 'auto'
          - type: button
            entity: switch.light_well
            state_color: true
            tap_action:
              action: call-service
              service: script.auto_switch_manual
              service_data:
                auto_switch: input_select.light_well
                target: switch.light_well
            hold_action:
              action: call-service
              service: input_select.select_option
              service_data:
                entity_id: input_select.light_well
                option: 'auto'
      - type: horizontal-stack
        cards:
          - type: button
            entity: switch.light_garage
            state_color: true
            tap_action:
              action: call-service
              service: script.auto_switch_manual
              service_data:
                auto_switch: input_select.light_garage
                target: switch.light_garage
            hold_action:
              action: call-service
              service: input_select.select_option
              service_data:
                entity_id: input_select.light_garage
                option: 'auto'
          - type: button
            entity: switch.light_cellar
            state_color: true
      - type: horizontal-stack
        cards:
          - type: button
            entity: switch.light_christmas_front
            state_color: true
            tap_action:
              action: call-service
              service: script.auto_switch_manual
              service_data:
                auto_switch: input_select.light_christmas_front
                target: switch.light_christmas_front
            hold_action:
              action: call-service
              service: input_select.select_option
              service_data:
                entity_id: input_select.light_christmas_front
                option: 'auto'
          - type: button
            entity: switch.light_christmas_tree
            state_color: true
            tap_action:
              action: call-service
              service: script.auto_switch_manual
              service_data:
                auto_switch: input_select.light_christmas_tree
                target: switch.light_christmas_tree
            hold_action:
              action: call-service
              service: input_select.select_option
              service_data:
                entity_id: input_select.light_christmas_tree
                option: 'auto'
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: button
                entity: switch.light_outside_1
                state_color: true
                tap_action:
                  action: call-service
                  service: script.auto_switch_manual
                  service_data:
                    auto_switch: input_select.light_outside_1
                    target: switch.light_outside_1
                hold_action:
                  action: call-service
                  service: input_select.select_option
                  service_data:
                    entity_id: input_select.light_outside_1
                    option: 'auto'
              - type: button
                entity: switch.light_outside_2
                state_color: true
                tap_action:
                  action: call-service
                  service: script.auto_switch_manual
                  service_data:
                    auto_switch: input_select.light_outside_2
                    target: switch.light_outside_2
                hold_action:
                  action: call-service
                  service: input_select.select_option
                  service_data:
                    entity_id: input_select.light_outside_2
                    option: 'auto'
              - type: button
                entity: switch.light_outside_3
                state_color: true
                tap_action:
                  action: call-service
                  service: script.auto_switch_manual
                  service_data:
                    auto_switch: input_select.light_outside_3
                    target: switch.light_outside_3
                hold_action:
                  action: call-service
                  service: input_select.select_option
                  service_data:
                    entity_id: input_select.light_outside_3
                    option: 'auto'
          - type: horizontal-stack
            cards:
              - type: button
                entity: switch.light_outside_4
                state_color: true
                tap_action:
                  action: call-service
                  service: script.auto_switch_manual
                  service_data:
                    auto_switch: input_select.light_outside_4
                    target: switch.light_outside_4
                hold_action:
                  action: call-service
                  service: input_select.select_option
                  service_data:
                    entity_id: input_select.light_outside_4
                    option: 'auto'
              - type: button
                entity: switch.light_outside_5
                state_color: true
                tap_action:
                  action: call-service
                  service: script.auto_switch_manual
                  service_data:
                    auto_switch: input_select.light_outside_5
                    target: switch.light_outside_5
                hold_action:
                  action: call-service
                  service: input_select.select_option
                  service_data:
                    entity_id: input_select.light_outside_5
                    option: 'auto'
              - type: button
                entity: switch.light_outside_6
                state_color: true
                tap_action:
                  action: call-service
                  service: script.auto_switch_manual
                  service_data:
                    auto_switch: input_select.light_outside_6
                    target: switch.light_outside_6
                hold_action:
                  action: call-service
                  service: input_select.select_option
                  service_data:
                    entity_id: input_select.light_outside_6
                    option: 'auto'
      - type: horizontal-stack
        cards:
          - type: entities
            entities:
              - input_select.light_driveway
              - input_select.light_gate_reflector
              - input_select.light_garage
              - input_select.light_christmas_front
              - input_select.light_christmas_tree
              - input_select.light_well
          - type: entities
            entities:
              - input_select.light_outside_1
              - input_select.light_outside_2
              - input_select.light_outside_3
              - input_select.light_outside_4
              - input_select.light_outside_5
              - input_select.light_outside_6
            state_color: true
      - type: vertical-stack
        cards:
        - type: horizontal-stack
          cards:
            - type: button
              entity: binary_sensor.motion_sensor_driveway_uppest
            - type: gauge
              entity: sensor.motion_sensor_driveway_uppest_average
              min: 0.0
              max: 1.0
        - type: horizontal-stack
          cards:
            - type: button
              entity: binary_sensor.motion_sensor_driveway_upper
            - type: gauge
              entity: sensor.motion_sensor_driveway_upper_average
              min: 0.0
              max: 1.0
        - type: horizontal-stack
          cards:
            - type: button
              entity: binary_sensor.motion_sensor_driveway_lower
            - type: gauge
              entity: sensor.motion_sensor_driveway_lower_average
              min: 0.0
              max: 1.0
        - type: horizontal-stack
          cards:
            - type: button
              entity: binary_sensor.motion_sensor_garage
            - type: gauge
              entity: sensor.motion_sensor_garage_average
              min: 0.0
              max: 1.0
        - type: horizontal-stack
          cards:
            - type: button
              entity: binary_sensor.motion_sensor_garage2
            - type: gauge
              entity: sensor.motion_sensor_garage2_average
              min: 0.0
              max: 1.0
        - type: horizontal-stack
          cards:
            - type: button
              entity: binary_sensor.motion_sensor_well
            - type: gauge
              entity: sensor.motion_sensor_well_average
              min: 0.0
              max: 1.0
        title: Mozgásérzékelők
        show_header_toggle: false
  - path: weather
    title: Időjárás
    badges: []
    cards:
      - type: glance
        entities:
          - sun.sun
          - sensor.moon
          - binary_sensor.night
        show_header_toggle: false
      - type: glance
        entities:
          - sensor.rain_last_day
          - sensor.rain_last_7_days
          - sensor.maximum_temperature_last_day
      - type: glance
        entities:
          - sensor.wind_strength
          - sensor.wind_direction
          - sensor.wind_direction_average
        show_header_toggle: false
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.temperature_outside
                graph: line
              # - type: sensor
              #   entity: sensor.humidity_outside
              #   graph: line
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.temperature_outside2
                graph: line
              - type: sensor
                entity: sensor.humidity_outside2
                graph: line
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.temperature_bedroom_upper
                graph: line
              - type: sensor
                entity: sensor.humidity_bedroom_upper
                graph: line
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.temperature_bedroom_lower
                graph: line
              - type: sensor
                entity: sensor.humidity_bedroom_lower
                graph: line
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.temperature_living_room_upper
                graph: line
              - type: sensor
                entity: sensor.humidity_living_room_upper
                graph: line
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.temperature_living_room_lower
                graph: line
              - type: sensor
                entity: sensor.humidity_living_room_lower
                graph: line
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.temperature_kitchen
                graph: line
              - type: sensor
                entity: sensor.humidity_kitchen
                graph: line
    icon: 'mdi:weather-pouring'
  - path: state
    title: state
    badges: []
    cards:
      - type: entities
        entities:
          - binary_sensor.network_available
          - binary_sensor.desktop_available
          - binary_sensor.internet_available
          - binary_sensor.gateway_available
          - binary_sensor.ssh_tunnel_available
          - binary_sensor.mosquitto_bridge_available
        title: Hálózat
        state_color: true
        show_header_toggle: false
      - type: entities
        entities:
          - binary_sensor.furnace_temperature_available
          - binary_sensor.well_controller_available
          - binary_sensor.main_controller_available
          - binary_sensor.main_controller2_available
          - binary_sensor.driveway_available
          - binary_sensor.cellar_controller_available
          - binary_sensor.living_room_temperature_available
          - binary_sensor.bedroom_temperature_available
          - binary_sensor.dishwasher_sensor_available
          - binary_sensor.gate_reflector_available
          - binary_sensor.attic_lower_available
        title: device_availability
        state_color: true
        show_header_toggle: false
      - type: entities
        entities:
          - sensor.furnace_temperature_free_memory
          - sensor.well_controller_free_memory
          - sensor.main_controller_free_memory
          - sensor.main_controller2_free_memory
          - sensor.driveway_free_memory
          - sensor.cellar_controller_free_memory
          - sensor.living_room_temperature_free_memory
          - sensor.bedroom_temperature_free_memory
          - sensor.dishwasher_sensor_free_memory
          - sensor.gate_reflector_free_memory
          - sensor.attic_lower_free_memory
        title: device_memory
        show_header_toggle: false
      - type: entities
        entities:
          - sensor.furnace_temperature_uptime
          - sensor.well_controller_uptime
          - sensor.main_controller_uptime
          - sensor.main_controller2_uptime
          - sensor.driveway_uptime
          - sensor.cellar_controller_uptime
          - sensor.living_room_temperature_uptime
          - sensor.bedroom_temperature_uptime
          - sensor.dishwasher_sensor_uptime
          - sensor.gate_reflector_uptime
          - sensor.attic_lower_uptime
        title: device_uptime
        show_header_toggle: false
      - type: entities
        entities:
          - sensor.tmp_free_space
          - sensor.var_log_free_space
        title: local_device
        show_header_toggle: false
      - type: entities
        entities:
          - sensor.apc_input_voltage
          - sensor.apc_battery_voltage
          - sensor.apc_battery_charge
          - sensor.apc_load
        title: local_device
        show_header_toggle: false
    icon: 'mdi:wrench'
