total_threads:
    module: expression
    class: Expression
    dependencies: [locker, admin_sync]
    target: sensor.total_threads
    expr: len(d.thread)
    attributes: {icon: mdi:counter}

active_threads:
    module: expression
    class: Expression
    dependencies: [locker, admin_sync]
    target: sensor.active_threads
    expr: 'sum(1 for x in d.thread if x != "idle")'
    attributes: {icon: mdi:progress-clock}

admin_sync:
    module: admin_sync
    class: AdminSync
    dependencies: locker
    attributes:
        sensor.active_apps: {icon: mdi:cog-play}
        sensor.inactive_apps: {icon: mdi:cog-stop}
        sensor.appdaemon_uptime: {icon: mdi:timer-outline}
        sensor.appdaemon_booted: {icon: mdi:calendar-start}

total_threads:
    module: expression
    class: Expression
    dependencies: [locker, admin_sync]
    target: binary_sensor.has_inactive_app
    expr: v.sensor.inactive_apps > 0
    attributes: {icon: mdi:alert}
