auto_switch_light_driveway:
    module: auto_switch
    class: AutoSwitch
    dependencies: locker
    target: switch.light_driveway
    switch: input_select.light_driveway
    reentrant: true


auto_switch_light_well:
    module: auto_switch
    class: AutoSwitch
    dependencies: locker
    target: switch.light_well
    switch: input_select.light_well
    reentrant: true


auto_switch_light_gate_reflector:
    module: auto_switch
    class: AutoSwitch
    dependencies: locker
    target: switch.light_gate_reflector
    switch: input_select.light_gate_reflector
    reentrant: true


auto_switch_light_garage:
    module: auto_switch
    class: AutoSwitch
    dependencies: locker
    target: switch.light_garage
    switch: input_select.light_garage
    reentrant: true


auto_switch_light_outside_0:
    module: auto_switch
    class: AutoSwitch
    dependencies: locker
    target: switch.light_outside_0
    switch: input_select.light_outside_0
    reentrant: true


auto_switch_light_outside_1:
    module: auto_switch
    class: AutoSwitch
    dependencies: locker
    target: switch.light_outside_1
    switch: input_select.light_outside_1
    reentrant: true


auto_switch_light_outside_2:
    module: auto_switch
    class: AutoSwitch
    dependencies: locker
    target: switch.light_outside_2
    switch: input_select.light_outside_2
    reentrant: true


auto_switch_light_outside_3:
    module: auto_switch
    class: AutoSwitch
    dependencies: locker
    target: switch.light_outside_3
    switch: input_select.light_outside_3
    reentrant: true


auto_switch_light_outside_4:
    module: auto_switch
    class: AutoSwitch
    dependencies: locker
    target: switch.light_outside_4
    switch: input_select.light_outside_4
    reentrant: true


auto_switch_light_outside_5:
    module: auto_switch
    class: AutoSwitch
    dependencies: locker
    target: switch.light_outside_5
    switch: input_select.light_outside_5
    reentrant: true


auto_switch_light_outside_6:
    module: auto_switch
    class: AutoSwitch
    dependencies: locker
    target: switch.light_outside_6
    switch: input_select.light_outside_6
    reentrant: true


light_outside_switcher_0:
    class: EnabledSwitch
    module: enabled_switch
    dependencies:
        - auto_switch_light_outside_0
        - sun_enabler_night
        - locker
    enabler: sun_enabler_night
    targets:
        - auto_switch_light_outside_0


light_outside_switcher_1:
    class: EnabledSwitch
    module: enabled_switch
    dependencies:
        - auto_switch_light_outside_1
        - sun_enabler_night
        - locker
    enabler: sun_enabler_night
    targets:
        - auto_switch_light_outside_1


light_outside_2_4_5_6_enabler:
    module: enabler
    class: ExpressionEnabler
    expr: >
        e.sun_enabler_night and e.lights_should_be_on
    dependencies:
        - sun_enabler_night
        - lights_should_be_on
        - locker


light_outside_switcher_2_4_5_6:
    class: EnabledSwitch
    module: enabled_switch
    dependencies:
        - auto_switch_light_outside_2
        - auto_switch_light_outside_4
        - auto_switch_light_outside_5
        - auto_switch_light_outside_6
        - locker
        - light_outside_2_4_5_6_enabler
    enabler: light_outside_2_4_5_6_enabler
    targets:
        - auto_switch_light_outside_2
        - auto_switch_light_outside_4
        - auto_switch_light_outside_5
        - auto_switch_light_outside_6


light_outside_switcher_3:
    class: EnabledSwitch
    module: enabled_switch
    dependencies:
        - auto_switch_light_outside_3
        - is_night_or_dark
        - locker
    enabler: is_night_or_dark
    targets:
        - auto_switch_light_outside_3

