window_blind_shield_1:
    module: enabler
    class: ExpressionEnabler
    expr: >
        v.input_select.season_mode == 'summer' and
        v.sensor.time >= '13:00' and
        v.sensor.time < '18:00' and
        e.is_sunlight_or_true
    dependencies:
        - locker
        - is_sunlight_or_true


dining_room_window_blind:
    module: cover
    class: CoverController
    dependencies:
        - locker
        - window_blind_shield_1
    expr: >
        75 if v.input_select.presence_mode == 'home' and e.window_blind_shield_1
        else 'open' if v.input_select.presence_mode == 'home' or (
        v.input_select.presence_mode == 'sleep' and
        v.binary_sensor.window_entrance) or (
        v.input_select.presence_mode == 'away' and
        e.is_sunlight_or_false and
        v.input_select.season_mode == 'winter')
        else 'closed'
    target: cover.dining_room
    mode_switch: input_select.dining_room_window_blind_1
    delay:
      seconds: 30


window_blind_shield_2:
    module: enabler
    class: ExpressionEnabler
    expr: >
        v.input_select.season_mode == 'summer' and
        v.sensor.time < '10:00' and
        not e.sun_enabler_night
    dependencies:
        - locker
        - sun_enabler_night


dining_room_2_window_blind:
    module: cover
    class: CoverController
    dependencies:
        - locker
        - is_light_enough_to_open_blind
        - window_blind_shield_2
    expr: >
        75 if v.input_select.presence_mode == 'home' and e.window_blind_shield_2
        else 'open' if v.input_select.presence_mode == 'home' and (
        e.is_light_enough_to_open_blind or v.binary_sensor.window_dining_room_2)
        else 'closed'
    target: cover.dining_room_2
    mode_switch: input_select.dining_room_window_blind_2
    delay:
      seconds: 30


auto_switch_storage_window_blind:
    module: auto_switch
    class: AutoSwitch
    dependencies: locker
    target: input_boolean.storage_window_blind_open
    reentrant: true


storage_window_blind_auto_open_enabler:
    module: enabler
    class: ExpressionEnabler
    expr: >
        v.input_select.presence_mode == 'home' and e.is_light_enough_to_open_blind
    dependencies:
        - is_light_enough_to_open_blind
        - locker


storage_door_open:
    class: TimerSwitch
    module: timer_switch
    dependencies:
        - auto_switch_storage_window_blind
        - storage_window_blind_auto_open_enabler
        - locker
    sensor: binary_sensor.door_storage
    targets:
        - auto_switch_storage_window_blind
    enabler: storage_window_blind_auto_open_enabler
    time: 60


storage_window_blind_enabler:
    module: enabler
    class: ExpressionEnabler
    dependencies:
        - locker
        - is_light_enough_to_open_blind
    expr: >
        v.input_select.presence_mode == 'home'
        and e.is_light_enough_to_open_blind
        and v.input_select.season_mode == 'winter'
    delay:
        seconds: 30


storage_window_blind_switch:
    class: EnabledSwitch
    module: enabled_switch
    dependencies:
        - storage_window_blind_enabler
        - locker
    enabler: storage_window_blind_enabler
    targets:
        - auto_switch_storage_window_blind


storage_window_blind_1:
    module: cover
    class: CoverController
    dependencies:
        - locker
        - auto_switch_storage_window_blind
    expr: >
        'open' if
        v.input_boolean.storage_window_blind_open or
        v.binary_sensor.window_storage_1
        else 'closed'
    mode_switch: input_select.storage_window_blind_1
    target: cover.storage_1


storage_window_blind_2:
    module: cover
    class: CoverController
    dependencies:
        - locker
        - auto_switch_storage_window_blind
    expr: >
        'open' if
        v.input_boolean.storage_window_blind_open or
        v.binary_sensor.window_storage_2
        else 'closed'
    mode_switch: input_select.storage_window_blind_2
    target: cover.storage_2


living_room_window_blind:
    module: cover
    class: CoverController
    dependencies:
        - locker
        - is_light_enough_to_open_blind
    expr: >
        'open' if v.input_select.presence_mode == 'home' and (
        e.is_light_enough_to_open_blind or v.binary_sensor.window_living_room)
        else 45 if (v.input_select.presence_mode == 'away' and
        e.is_light_enough_to_open_blind) or (
        v.input_select.presence_mode == 'sleep' and
        v.binary_sensor.window_living_room)
        else 'closed'
    target: cover.living_room
    mode_switch: input_select.living_room_window_blind
    delay:
        seconds: 10

